/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import { Scene } from "laya/display/Scene";
import { ClassUtils } from "laya/utils/ClassUtils";
var REG: Function = ClassUtils.regClass;
import { Text } from "laya/display/Text";
import { Image } from "laya/ui/Image";
export module ui.test {
    export class TestSceneUI extends Scene {
		public question:Text;
		public pics:Image;
        public referenceClass:Array<any>=[Text, Image]; // 强制引用类,防止被编译器忽略
		constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("test/TestScene");
        }
    }
    REG("ui.test.TestSceneUI",TestSceneUI);
}